// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzK2hdE4R4i6MYIjITUjVkZMJWVYsOGjY',
    appId: '1:872277913018:web:543d1d1d98c9fcbb520183',
    messagingSenderId: '872277913018',
    projectId: 'my-notes-anu',
    authDomain: 'my-notes-anu.firebaseapp.com',
    storageBucket: 'my-notes-anu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyjlrThaKe2TLVNw6E1cSna-wEO_RG87c',
    appId: '1:872277913018:android:b8bbf776ebeb4b93520183',
    messagingSenderId: '872277913018',
    projectId: 'my-notes-anu',
    storageBucket: 'my-notes-anu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjSI4HyCzDWd39bSdpfIfbye748Cu44TM',
    appId: '1:872277913018:ios:38ccaeaaccbffc73520183',
    messagingSenderId: '872277913018',
    projectId: 'my-notes-anu',
    storageBucket: 'my-notes-anu.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjSI4HyCzDWd39bSdpfIfbye748Cu44TM',
    appId: '1:872277913018:ios:38ccaeaaccbffc73520183',
    messagingSenderId: '872277913018',
    projectId: 'my-notes-anu',
    storageBucket: 'my-notes-anu.firebasestorage.app',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzK2hdE4R4i6MYIjITUjVkZMJWVYsOGjY',
    appId: '1:872277913018:web:c6cdc53849d2dbfe520183',
    messagingSenderId: '872277913018',
    projectId: 'my-notes-anu',
    authDomain: 'my-notes-anu.firebaseapp.com',
    storageBucket: 'my-notes-anu.firebasestorage.app',
  );
}
